#! /bin/sh

## Environment 
# export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Java Applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING

# Startup
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
# picom --config ~/.config/picom/picom.conf
$HOME/.config/polybar/launch.sh

# dunst &

feh --bg-fill /usr/share/backgrounds/wallpaper.jpg
# feh --bg-fill -z ~/Pictures
# wal -i ~/.config/bspwm/wallpapers

# EndStartup

# bspc monitor -d ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '
bspc monitor -d I II III IV V VI VII VIII IX X

colors(){
	foreground=#CDD6F4
	background=#1E1E2E
}
colors

bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.50

bspc config focused_border_color	   "#F38BA8"
bspc config normal_border_color		"$background"
bspc config active_border_color		"$foreground"

bspc config borderless_monocle   	true
# bspc config gapless_monocle      	true
bspc config paddingless_monocle	 	true
bspc config single_monocle		 	   true
bspc config focus_follows_pointer	true

# bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# 4 > files
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 3 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

#  6 > Communication
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > media
declare -a media=(Audacity vlc Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

# 8 > settings
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off